SKILL_ALIASES = {
    # AI / ML
    "ai/ml": "ai",
    "artificial intelligence": "ai",
    "artificial intelligence (ai)": "ai",
    "generative ai": "ai",
    "gen ai": "ai",
    "genai": "ai",
    "large language model": "llm",
    "large language models": "llm",
    "large language models (llms)": "llm",
    "llms": "llm",
    "machine learning (ml)": "machine learning",
    "machine learning basics": "machine learning",
    "machine learning development": "machine learning",
    "machine learning engineering": "machine learning",
    "ml": "machine learning",
    "deep learning frameworks": "deep learning",
    "dl": "deep learning",
    "natural language processing": "nlp",
    "natural language processing (nlp)": "nlp",
    "computer vision ai": "computer vision",
    "scikitlearn": "scikit-learn",
    "sklearn": "scikit-learn",
    "torch": "pytorch",
    "tf": "tensorflow",
    "tensorflow basics": "tensorflow",
    "pytorch basics": "pytorch",

    # Cloud services
    "amazon aws": "aws",
    "amazon cloud": "aws",
    "amazon web services": "aws",
    "amazon web services (aws)": "aws",
    "aws cloud": "aws",
    "aws cloud native": "aws",
    "aws cloudbased services": "aws",
    "aws services": "aws",
    "aws tools": "aws",
    "aws tools and services": "aws",
    "aws/ec2": "aws ec2",
    "aws  ecs": "aws ecs",
    "aws elasticache": "aws elasticache",
    "aws solution architect associate": "aws solutions architect associate",
    "aws solutions architect  associate": "aws solutions architect associate",
    "cloud formation": "cloudformation",
    "cloud functions": "google cloud functions",
    "cloud sql": "google cloud sql",
    "gcp": "gcp",
    "google cloud": "gcp",
    "google cloud platform": "gcp",
    "google cloud platform (gcp)": "gcp",
    "google cloud storage": "gcp",
    "google big query": "bigquery",
    "google bigquery": "bigquery",
    "big query": "bigquery",
    "azure cloud": "azure",
    "azure cloud services": "azure",
    "azure event hub": "azure event hub",
    "azure eventhub": "azure event hub",
    "azure sql": "azure sql",
    "microsoft azure": "azure",

    # Languages
    "c plus plus": "c++",
    "cplusplus": "c++",
    "c/c#": "c/c++",
    "c#/c++": "c/c++",
    "c sharp": "c#",
    "c-sharp": "c#",
    "golang": "go",
    "java.": "java",
    "java 8+": "java 8",
    "java script": "javascript",
    "javascript  es6": "javascript",
    "javascript (es5 and es6/es2015)": "javascript",
    "javascript (es5/6)": "javascript",
    "javascript (es6 and jquery)": "javascript",
    "javascript (es6+)": "javascript",
    "javascript (or typescript)": "javascript",
    "javascript/typescript": "javascript",
    "js": "javascript",
    "modern javascipt framework": "modern javascript framework",
    "ts": "typescript",
    "proficiency in typescript programming": "typescript",
    "objective c": "objective-c",
    "objectivec": "objective-c",
    "shell scripting": "bash",
    "shell script": "bash",
    "unix shell": "bash",

    # .NET
    ".net/core": ".net core",
    ".netcore": ".net core",
    ".net 6+": ".net 6",
    ".net6": ".net 6",
    ".net 6.0": ".net 6",
    ".net7/8": ".net",
    "asp .net": "asp.net",
    "asp .net core": "asp.net core",
    "c# .net": "c#.net",
    "entity framework": "entityframework",
    "entityframework core": "entityframework",

    # Frontend frameworks and libraries
    "angular js": "angular",
    "angular.js": "angular",
    "angularjs": "angular",
    "angular 13+": "angular 13",
    "angular/react": "angular",
    "google angular framework": "angular",
    "backbone js": "backbone.js",
    "backbonejs": "backbone.js",
    "d3js": "d3.js",
    "emberjs": "ember.js",
    "express.js": "express",
    "expressjs": "express",
    "fast api": "fastapi",
    "frameworks (react/next.js/svelte)": "react",
    "html 5": "html",
    "html5": "html",
    "css3": "css",
    "html5 & css3": "html/css",
    "html5 / css3": "html/css",
    "html5/css3": "html/css",
    "html/css/javascript": "html/css",
    "jquery": "jquery",
    "j query": "jquery",
    "knockoutjs": "knockout.js",
    "material ui": "materialui",
    "micro front ends": "micro frontends",
    "microfrontend": "micro frontends",
    "nest js": "nestjs",
    "nest.js": "nestjs",
    "next js": "next.js",
    "nextjs": "next.js",
    "nextjs/vercel": "next.js",
    "node": "node.js",
    "node js": "node.js",
    "nodejs": "node.js",
    "nodes.js": "node.js",
    "node/express": "node.js",
    "express/node": "node.js",
    "preact": "react",
    "react js": "react",
    "react.js": "react",
    "reactjs": "react",
    "advanced react": "react",
    "advanced react (hooks": "react",
    "classbased react": "react",
    "react basics": "react",
    "react best practices": "react",
    "react component design patterns": "react",
    "react component libraries": "react",
    "react components": "react",
    "react design patterns": "react",
    "react ecosystem": "react",
    "react metaframework experience": "react",
    "react next.js": "react",
    "react/angular": "react",
    "react/redux": "react",
    "react vue.js blazor": "react",
    "reactnative": "react native",
    "rn": "react native",
    "react query": "react query",
    "reactquery": "react query",
    "react router": "react router",
    "react spring": "react spring",
    "react testinglibrary": "react testing library",
    "reacttestinglibrary": "react testing library",
    "redux)": "redux",
    "redux saga": "redux",
    "redux toolkit": "redux",
    "tailwindcss": "tailwind css",
    "threejs": "three.js",
    "ui": "ui/ux",
    "ux": "ui/ux",
    "ux/ui": "ui/ux",
    "ui / ux design": "ui/ux",
    "ui/ux design": "ui/ux",
    "vue": "vue.js",
    "vue js": "vue.js",
    "vuejs": "vue.js",
    "vue 2": "vue.js",
    "vue 3": "vue.js",
    "vue.js basics": "vue.js",
    "webapi": "web api",
    "web assembly": "webassembly",
    "web components": "webcomponents",
    "web sockets": "websockets",

    # Backend and architecture
    "api's": "apis",
    "api gateway": "apigateway",
    "api based software development": "api based software development",
    "http/rest": "http rest",
    "http/s": "https",
    "restapi": "rest api",
    "rest assured": "restassured",
    "service oriented architecture": "serviceoriented architecture",
    "event driven architecture": "eventdriven architecture",
    "domain driven design": "domaindriven design",
    "object oriented design": "objectoriented design",
    "object oriented design (ood)": "objectoriented design (ood)",
    "object oriented programming": "objectoriented programming",
    "object oriented programming (oop)": "objectoriented programming (oop)",
    "micro services": "microservices",
    "microservice": "microservices",
    "service now": "servicenow",
    "spring boot": "springboot",
    "spring batch": "springbatch",
    "java (spring)": "java spring",
    "java spring boot": "spring boot",
    "web services": "webservices",

    # Databases and query languages
    "db": "database",
    "database": "database",
    "dbms": "database management system",
    "rdbms": "relational database",
    "mariadb": "mysql",
    "mysql / mariadb": "mysql",
    "mysql/mariadb": "mysql",
    "pgsql": "postgresql",
    "postgres": "postgresql",
    "postgres sql": "postgresql",
    "postgresdb": "postgresql",
    "postgressql": "postgresql",
    "postresql": "postgresql",
    "microsoft sql": "sql server",
    "microsoft sql server": "sql server",
    "ms sql": "sql server",
    "ms sql server": "sql server",
    "mssql": "sql server",
    "sqlserver": "sql server",
    "sql server 2008": "sql server",
    "sql server 2017": "sql server",
    "sql server 2019": "sql server",
    "sql server 2022": "sql server",
    "sql server db": "sql server",
    "sql server database development": "sql server",
    "sql database": "sql",
    "sql databases": "sql",
    "sql experience": "sql",
    "sql queries": "sql",
    "sql scripting": "sql",
    "sql scripts": "sql",
    "structured query language (sql)": "sql",
    "transactsql": "tsql",
    "oracle/sql": "oracle sql",
    "oracle sql": "pl/sql",
    "sql alchemy": "sqlalchemy",
    "sqlite": "sql",
    "cosmos db": "cosmosdb",
    "influx db": "influxdb",
    "open search": "opensearch",
    "elastic search": "elasticsearch",
    "open source databases": "opensource databases",
    "open sourcedatabases": "opensource databases",
    "opensource databases": "opensource databases",
    "document database": "nosql",
    "document databases": "nosql",
    "nosql db": "nosql",
    "nosql databases": "nosql",
    "nosql storage": "nosql",
    "nosql technologies": "nosql",
    "rabbit mq": "rabbitmq",

    # Data engineering, analytics, and BI
    "big data analytics": "bigdata analytics",
    "data warehouse": "data warehouse",
    "datawarehouse": "data warehouse",
    "data warehousing": "data warehouse",
    "meta data management": "metadata management",
    "map reduce": "mapreduce",
    "powerbi": "power bi",
    "looker studio": "looker",
    "google analytics 4": "google analytics",
    "ga4": "google analytics",
    "spark sql": "spark",
    "apache spark": "spark",
    "apache hadoop": "hadoop",
    "apache hive": "hive",
    "apache kafka": "kafka",
    "extract transform load": "etl",
    "extract/transform/load": "etl",
    "extract transform load (etl)": "etl",
    "elt/etl": "etl",

    # DevOps, source control, and infrastructure
    "ci cd": "ci/cd",
    "ci-cd": "ci/cd",
    "cicd": "ci/cd",
    "ci/cd automation": "ci/cd",
    "ci/cd deployment pipelines": "ci/cd",
    "ci/cd pipeline": "ci/cd",
    "ci/cd pipelines": "ci/cd",
    "ci/cd solutions": "ci/cd",
    "ci/cd stack": "ci/cd",
    "ci/cd systems": "ci/cd",
    "ci/cd toolchain": "ci/cd",
    "ci/cd tooling": "ci/cd",
    "ci/cd tools": "ci/cd",
    "continuous integration / continuous delivery (ci/cd)": "ci/cd",
    "continuous integration/continuous delivery (ci/cd)": "ci/cd",
    "continuous integration/continuous deployment (ci/cd)": "ci/cd",
    "continuous integration/continuous development (ci/cd)": "ci/cd",
    "circleci/github actions": "github actions",
    "github action": "github actions",
    "git (github/gitlab)": "git",
    "github/gitlab": "git",
    "gitlab ci": "gitlab ci/cd",
    "gitlab ci/cd": "gitlab ci/cd",
    "gitlabci/cd": "gitlab ci/cd",
    "gitlab runners": "gitlab",
    "source control": "version control",
    "sourcecontrol": "version control",
    "source control tools": "version control",
    "versioning": "version control",
    "docker basics": "docker",
    "docker containers": "docker",
    "docker-compose": "docker compose",
    "dockerization": "docker",
    "containerization (docker)": "docker",
    "containerization (docker kubernetes)": "docker",
    "containerization technologies (docker kubernetes)": "docker",
    "k8s": "kubernetes",
    "k8s (eks)": "kubernetes",
    "kubernetes basics": "kubernetes",
    "google kubernetes engine": "kubernetes",
    "gcp & kubernetes": "kubernetes",
    "hashicorp terraform": "terraform",
    "terraform/cloud formation": "terraform",
    "infrastructure as code": "infrastructureascode",
    "infrastructure as code solutions (terraform pulumi)": "infrastructureascode",
    "jenkins/travis": "jenkins",
    "team city": "teamcity",
    "sumo logic": "sumologic",
    "new relic": "newrelic",
    "dev*ops": "devops",

    # Testing and QA
    "automation test": "automation testing",
    "automated testing": "automation testing",
    "automated software testing": "automation testing",
    "automated test environments": "automation testing",
    "automated test strategies": "automation testing",
    "automated test suites": "automation testing",
    "automated testing frameworks": "automation testing",
    "automated testing tools": "automation testing",
    "automated unit testing": "unit testing",
    "endtoend testing": "e2e testing",
    "endtoend testing (cypress)": "e2e testing",
    "e2e tests": "e2e testing",
    "frontend testing": "testing",
    "functional testing": "testing",
    "integration tests": "integration testing",
    "jest testing framework": "jest",
    "ms test": "mstest",
    "nunit unit testing": "unit testing",
    "pytest advanced": "pytest",
    "pytest basics": "pytest",
    "selenium webdriver": "selenium",
    "software testing and debugging": "software testing",
    "software testing methodologies": "software testing",
    "test automation tools": "test automation",
    "test driven development": "tdd",
    "testdriven development": "tdd",
    "test driven development (tdd)": "tdd",
    "testdriven development (tdd)": "tdd",
    "tdd (test driven development)": "tdd",
    "behavior driven development": "bdd",
    "behaviordriven development": "bdd",
    "behavior driven development (bdd)": "bdd",
    "behaviordriven development (bdd)": "bdd",

    # Security
    "cyber security": "cybersecurity",
    "security+": "security",
    "application security": "security",
    "appsec": "security",
    "identity access management": "iam",
    "identity and access management": "iam",
    "access control": "iam",
    "penetration test": "penetration testing",
    "pen testing": "penetration testing",
    "pentesting": "penetration testing",
    "vulnerability assessment.": "vulnerability assessment",
    "web application security": "security",

    # Methodologies and soft skills that appear in job skill fields
    "agile scrum": "agile",
    "agile/scrum": "agile",
    "agile development": "agile",
    "agile practices": "agile",
    "scrum agile": "scrum",
    "kanban agile": "kanban",
    "problem solving": "problem solving",
    "problem-solving": "problem solving",
    "problemsolving": "problem solving",
    "decision making": "decision making",
    "decisionmaking": "decision making",
    "technical decision making": "technical decision making",
    "technical decisionmaking": "technical decision making",
    "team work": "teamwork",
    "time management": "time management",
    "timemanagement": "time management",
    "self motivation": "self motivation",
    "selfmotivation": "self motivation",
    "cross functional collaboration": "crossfunctional collaboration",
    "cross functional teams": "crossfunctional teams",

    # Product/domain terms with common formatting variants
    "active mq": "activemq",
    "bare metal operations": "baremetal operations",
    "boot loaders": "bootloaders",
    "client/server architectures": "clientserver architectures",
    "client/server programming": "clientserver programming",
    "cloud based applications": "cloudbased applications",
    "cloud based infrastructure": "cloudbased infrastructure",
    "cloud native": "cloudnative",
    "cloud native application development": "cloudnative application development",
    "cloud native applications": "cloudnative applications",
    "cloud native development": "cloudnative development",
    "cloud native technologies": "cloudnative technologies",
    "code pipeline": "codepipeline",
    "data center technologies": "datacenter technologies",
    "dev extreme": "devextreme",
    "ethernet/ip": "ethernet ip",
    "fault tolerance": "faulttolerance",
    "file systems": "filesystems",
    "free rtos": "freertos",
    "front end": "frontend",
    "front end development": "frontend development",
    "front end software engineering": "frontend software engineering",
    "full stack": "fullstack",
    "full stack development": "fullstack development",
    "full stack engineer": "fullstack engineer",
    "full stack engineering": "fullstack engineering",
    "full stack software engineer": "fullstack software engineer",
    "full stack software engineering": "fullstack software engineering",
    "green field projects": "greenfield projects",
    "health care": "healthcare",
    "high availability": "highavailability",
    "high performance computing": "highperformance computing",
    "high quality code": "highquality code",
    "hp alm": "hpalm",
    "iec 61850": "iec61850",
    "iec 62304": "iec62304",
    "iso 13485": "iso13485",
    "iso 14971": "iso14971",
    "iso 26262": "iso26262",
    "mac os": "macos",
    "matlab/simulink": "matlab simulink",
    "micro python": "micropython",
    "model based design": "modelbased design",
    "model based engineering": "modelbased engineering",
    "model based systems engineering": "modelbased systems engineering",
    "opc-ua": "opcua",
    "open source frameworks": "opensource frameworks",
    "open source libraries": "opensource libraries",
    "open source rdbms": "opensource rdbms",
    "open source software": "opensource software",
    "pair programming": "pairprogramming",
    "pub/sub": "pubsub",
    "qt/qml": "qt qml",
    "real time": "realtime",
    "real time operating systems": "realtime operating systems",
    "red hat": "redhat",
    "red hat enterprise linux": "redhat enterprise linux",
    "root cause analysis": "rootcause analysis",
    "software development life cycle": "software development lifecycle",
    "software development life cycle (sdlc)": "software development lifecycle (sdlc)",
    "software life cycle management": "software lifecycle management",
    "trunk based development": "trunkbased development",
    "u.s. citizenship": "us citizenship",
    "user interfaces": "userinterfaces",
    "user space": "userspace",
    "vs code": "vscode",
}


SKILL_COVERAGE = {
    # Specific SQL databases imply general SQL ability for matching/scoring.
    "mysql": ["sql", "database"],
    "postgresql": ["sql", "database"],
    "sql server": ["sql", "database"],
    "mariadb": ["sql", "database"],
    "oracle": ["sql", "database"],
    "oracle sql": ["sql", "database"],
    "pl/sql": ["sql", "database"],
    "sqlite": ["sql", "database"],
    "tsql": ["sql", "database"],
    "db2": ["sql", "database"],
    "snowflake": ["sql", "data warehouse"],
    "redshift": ["sql", "data warehouse"],
    "bigquery": ["sql", "data warehouse"],
    "mongodb": ["nosql", "database"],
    "cassandra": ["nosql", "database"],
    "dynamodb": ["nosql", "database"],
    "redis": ["nosql", "database"],
    "cosmosdb": ["nosql", "database"],
    "elasticsearch": ["search", "database"],

    # Cloud providers imply general cloud exposure.
    "aws": ["cloud"],
    "azure": ["cloud"],
    "gcp": ["cloud"],
    "oracle cloud": ["cloud"],
    "alicloud": ["cloud"],
    "aws ec2": ["aws", "cloud"],
    "aws ecs": ["aws", "cloud"],
    "aws lambda": ["aws", "cloud"],
    "aws s3": ["aws", "cloud"],
    "aws rds": ["aws", "cloud", "database"],
    "azure functions": ["azure", "cloud"],
    "azure devops": ["azure", "devops"],
    "google cloud sql": ["gcp", "cloud", "sql"],
    "google cloud functions": ["gcp", "cloud"],

    # Frontend frameworks imply frontend/web development foundations.
    "react": ["frontend development", "javascript"],
    "react native": ["mobile development", "javascript"],
    "vue.js": ["frontend development", "javascript"],
    "angular": ["frontend development", "javascript"],
    "next.js": ["frontend development", "react", "javascript"],
    "svelte": ["frontend development", "javascript"],
    "jquery": ["frontend development", "javascript"],
    "redux": ["frontend development", "javascript"],
    "tailwindcss": ["frontend development", "css"],
    "bootstrap": ["frontend development", "css"],
    "html": ["frontend development"],
    "css": ["frontend development"],
    "html/css": ["frontend development", "html", "css"],
    "typescript": ["javascript"],

    # Backend frameworks imply backend/API development.
    "node.js": ["backend development", "javascript"],
    "express": ["backend development", "node.js", "javascript"],
    "nestjs": ["backend development", "node.js", "typescript"],
    "django": ["backend development", "python"],
    "flask": ["backend development", "python"],
    "fastapi": ["backend development", "python"],
    "spring boot": ["backend development", "java"],
    "java spring": ["backend development", "java"],
    "laravel": ["backend development", "php"],
    "ruby on rails": ["backend development", "ruby"],
    "restapi": ["api"],
    "graphql": ["api"],

    # DevOps tools imply broader delivery/infrastructure skills.
    "docker": ["devops", "containerization"],
    "docker compose": ["docker", "containerization"],
    "docker swarm": ["docker", "containerization"],
    "kubernetes": ["devops", "container orchestration", "containerization"],
    "jenkins": ["ci/cd", "devops"],
    "github actions": ["ci/cd", "devops"],
    "gitlab ci/cd": ["ci/cd", "devops"],
    "terraform": ["infrastructureascode", "devops"],
    "ansible": ["automation", "devops"],
    "prometheus": ["monitoring", "devops"],
    "grafana": ["monitoring", "devops"],
    "datadog": ["monitoring", "devops"],
    "splunk": ["monitoring", "security"],
    "git": ["version control"],
    "github": ["git", "version control"],
    "gitlab": ["git", "version control"],
    "bitbucket": ["git", "version control"],

    # Testing tools imply testing/QA ability.
    "jest": ["testing", "frontend testing"],
    "cypress": ["testing", "frontend testing", "e2e testing"],
    "playwright": ["testing", "frontend testing", "e2e testing"],
    "selenium": ["testing", "e2e testing"],
    "pytest": ["testing", "unit testing", "python"],
    "mstest": ["testing", "unit testing"],
    "junit": ["testing", "unit testing", "java"],
    "nunit": ["testing", "unit testing"],
    "tdd": ["testing"],
    "bdd": ["testing"],
    "test automation": ["testing", "automation testing"],
    "automation testing": ["testing"],

    # Data/BI tools imply analytics/data handling.
    "tableau": ["data visualization", "business intelligence"],
    "powerbi": ["data visualization", "business intelligence"],
    "looker": ["data visualization", "business intelligence"],
    "excel": ["data analysis"],
    "google analytics": ["data analysis"],
    "spark": ["big data", "data engineering"],
    "hadoop": ["big data", "data engineering"],
    "hive": ["big data", "data engineering"],
    "kafka": ["data streaming", "data engineering"],
    "etl": ["data engineering"],
    "elt": ["data engineering"],
    "data warehouse": ["data engineering"],
    "data modeling": ["data engineering", "data analysis"],

    # AI/ML libraries imply broader ML skill.
    "tensorflow": ["machine learning", "deep learning"],
    "pytorch": ["machine learning", "deep learning"],
    "scikit-learn": ["machine learning"],
    "pandas": ["data analysis", "python"],
    "numpy": ["data analysis", "python"],
    "nlp": ["machine learning"],
    "computer vision": ["machine learning"],
    "llm": ["ai", "machine learning"],
    "rag": ["llm", "ai"],
    "langchain": ["llm", "ai"],
    "openai": ["llm", "ai"],
    "prompt engineering": ["llm", "ai"],

    # Security tools/practices imply security.
    "owasp": ["security"],
    "penetration testing": ["security"],
    "firewall": ["security", "network security"],
    "siem": ["security"],
    "qradar": ["security", "siem"],
    "cissp": ["security"],
    "cism": ["security"],
    "ceh": ["security"],
    "iam": ["security"],
    "vpn": ["network security"],
}
